### ISSUE TITLE
Provide better feedback if timing parameters need to be customized

### ISSUE THREAD

**Issue by nirvdrum** [benchmark-driver/benchmark-driver#31]
The default timing parameters in benchmark_driver work very well if you're performing a fast micro benchmark. However, if the code being benchmarked runs a bit slower, the default parameters for the warmup phase result in `__bmdv_ip100ms` being `0` due to the `.floor` call. And subsequently the `__bmdv_loops` value ends up being `0`. This will eventually lead to the following cryptic backtrace:

```
/home/kjmenard/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/benchmark_driver-0.10.15/lib/benchmark_driver/output/compare.rb:108:in `humanize': Non positive value: 0.0 (ArgumentError)
	from /home/kjmenard/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/benchmark_driver-0.10.15/lib/benchmark_driver/output/compare.rb:75:in `report'
	from /home/kjmenard/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/benchmark_driver-0.10.15/lib/benchmark_driver/runner/ips.rb:38:in `block (3 levels) in run'
	from /home/kjmenard/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/benchmark_driver-0.10.15/lib/benchmark_driver/output/compare.rb:55:in `with_job'
	from /home/kjmenard/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/benchmark_driver-0.10.15/lib/benchmark_driver/runner/ips.rb:34:in `block (2 levels) in run'
	from /home/kjmenard/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/benchmark_driver-0.10.15/lib/benchmark_driver/runner/ips.rb:31:in `map'
	from /home/kjmenard/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/benchmark_driver-0.10.15/lib/benchmark_driver/runner/ips.rb:31:in `block in run'
	from /home/kjmenard/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/benchmark_driver-0.10.15/lib/benchmark_driver/output/compare.rb:19:in `block in with_warmup'
	from /home/kjmenard/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/benchmark_driver-0.10.15/lib/benchmark_driver/output/compare.rb:101:in `without_stdout_buffering'
	from /home/kjmenard/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/benchmark_driver-0.10.15/lib/benchmark_driver/output/compare.rb:16:in `with_warmup'
	from /home/kjmenard/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/benchmark_driver-0.10.15/lib/benchmark_driver/runner/ips.rb:30:in `run'
	from /home/kjmenard/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/benchmark_driver-0.10.15/lib/benchmark_driver/runner.rb:36:in `block (2 levels) in run'
	from /home/kjmenard/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/benchmark_driver-0.10.15/lib/benchmark_driver/runner.rb:56:in `block in with_clean_env'
	from /home/kjmenard/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler.rb:297:in `block in with_clean_env'
	from /home/kjmenard/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler.rb:540:in `with_env'
	from /home/kjmenard/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler.rb:297:in `with_clean_env'
	from /home/kjmenard/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/benchmark_driver-0.10.15/lib/benchmark_driver/runner.rb:55:in `with_clean_env'
	from /home/kjmenard/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/benchmark_driver-0.10.15/lib/benchmark_driver/runner.rb:35:in `block in run'
	from /home/kjmenard/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/benchmark_driver-0.10.15/lib/benchmark_driver/runner.rb:29:in `each'
	from /home/kjmenard/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/benchmark_driver-0.10.15/lib/benchmark_driver/runner.rb:29:in `run'
	from /home/kjmenard/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/benchmark_driver-0.10.15/exe/benchmark-driver:104:in `<top (required)>'
	from /home/kjmenard/.rbenv/versions/2.4.4/bin/benchmark-driver:23:in `load'
	from /home/kjmenard/.rbenv/versions/2.4.4/bin/benchmark-driver:23:in `<main>'
```

I think the error should be handled with hints on how to tune the process to get better results. Note, however, that even for seemingly simple benchmarks I had to increase the run duration to many minutes just to get the parameter values to work. This seemed to be far in excess of what was needed to actually warm up. I think it may be worth revisiting when to determine warm up has completed.

**Comment by k0kubun** [comment]
Yeah, I want to improve the situation. Could you give me some example benchmark definitions to be fixed?
