### ISSUE TITLE
The "--output gruff" option will fail when contexts is specified.

### ISSUE THREAD

**Issue by naitoh** [benchmark-driver/benchmark-driver#38]
## No Problem case

```
$ cat test.yaml 

#contexts:
#  - gems: { csv: 1.0.0}

loop_count: 2000000
prelude: |
  class Array
    alias_method :blank?, :empty?
  end
  array = []
benchmark:
  empty: array.empty?
  blank: array.blank?
```

```
$ benchmark-driver test.yaml --output gruff
* empty...
  * 2.5.1...
* blank...
  * 2.5.1...
rendering graph...: graph.png
```

## Problem case

```
$ cat test.yaml 

contexts:
  - gems: { csv: 1.0.0}

loop_count: 2000000
prelude: |
  class Array
    alias_method :blank?, :empty?
  end
  array = []
benchmark:
  empty: array.empty?
  blank: array.blank?
```

```
$ benchmark-driver test.yaml --output gruff
* empty...
  * csv 1.0.0...
* blank...
  * csv 1.0.0...
rendering graph...Traceback (most recent call last):
	25: from /home/naitoh/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:15:in `<main>'
	24: from /home/naitoh/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:15:in `eval'
	23: from /home/naitoh/.rvm/gems/ruby-2.5.1/bin/benchmark-driver:23:in `<main>'
	22: from /home/naitoh/.rvm/gems/ruby-2.5.1/bin/benchmark-driver:23:in `load'
	21: from /home/naitoh/.rvm/gems/ruby-2.5.1/gems/benchmark_driver-0.13.3/exe/benchmark-driver:111:in `<top (required)>'
	20: from /home/naitoh/.rvm/gems/ruby-2.5.1/gems/benchmark_driver-0.13.3/lib/benchmark_driver/runner.rb:30:in `run'
	19: from /home/naitoh/.rvm/gems/ruby-2.5.1/gems/benchmark_driver-0.13.3/lib/benchmark_driver/runner.rb:30:in `each'
	18: from /home/naitoh/.rvm/gems/ruby-2.5.1/gems/benchmark_driver-0.13.3/lib/benchmark_driver/runner.rb:31:in `block in run'
	17: from /home/naitoh/.rvm/gems/ruby-2.5.1/gems/benchmark_driver-0.13.3/lib/benchmark_driver/runner.rb:31:in `each'
	16: from /home/naitoh/.rvm/gems/ruby-2.5.1/gems/benchmark_driver-0.13.3/lib/benchmark_driver/runner.rb:32:in `block (2 levels) in run'
	15: from /home/naitoh/.rvm/gems/ruby-2.5.1/gems/benchmark_driver-0.13.3/lib/benchmark_driver/runner.rb:32:in `each'
	14: from /home/naitoh/.rvm/gems/ruby-2.5.1/gems/benchmark_driver-0.13.3/lib/benchmark_driver/runner.rb:41:in `block (3 levels) in run'
	13: from /home/naitoh/.rvm/gems/ruby-2.5.1/gems/benchmark_driver-0.13.3/lib/benchmark_driver/runner.rb:93:in `with_clean_env'
	12: from /home/naitoh/.rvm/gems/ruby-2.5.1/gems/bundler-1.16.1/lib/bundler.rb:297:in `with_clean_env'
	11: from /home/naitoh/.rvm/gems/ruby-2.5.1/gems/bundler-1.16.1/lib/bundler.rb:540:in `with_env'
	10: from /home/naitoh/.rvm/gems/ruby-2.5.1/gems/bundler-1.16.1/lib/bundler.rb:297:in `block in with_clean_env'
	 9: from /home/naitoh/.rvm/gems/ruby-2.5.1/gems/benchmark_driver-0.13.3/lib/benchmark_driver/runner.rb:94:in `block in with_clean_env'
	 8: from /home/naitoh/.rvm/gems/ruby-2.5.1/gems/benchmark_driver-0.13.3/lib/benchmark_driver/runner.rb:42:in `block (4 levels) in run'
	 7: from /home/naitoh/.rvm/gems/ruby-2.5.1/gems/benchmark_driver-0.13.3/lib/benchmark_driver/runner/ips.rb:50:in `run'
	 6: from /home/naitoh/.rvm/gems/ruby-2.5.1/gems/benchmark_driver-0.13.3/lib/benchmark_driver/output.rb:55:in `with_benchmark'
	 5: from /home/naitoh/.rvm/gems/ruby-2.5.1/gems/benchmark_driver-0.13.3/lib/benchmark_driver/bulk_output.rb:36:in `with_benchmark'
	 4: from /home/naitoh/.rvm/gems/ruby-2.5.1/gems/benchmark_driver-output-gruff-0.3.0/lib/benchmark_driver/output/gruff.rb:42:in `bulk_output'
	 3: from /home/naitoh/.rvm/gems/ruby-2.5.1/gems/benchmark_driver-output-gruff-0.3.0/lib/benchmark_driver/output/gruff.rb:42:in `each'
	 2: from /home/naitoh/.rvm/gems/ruby-2.5.1/gems/benchmark_driver-output-gruff-0.3.0/lib/benchmark_driver/output/gruff.rb:43:in `block in bulk_output'
	 1: from /home/naitoh/.rvm/gems/ruby-2.5.1/gems/benchmark_driver-output-gruff-0.3.0/lib/benchmark_driver/output/gruff.rb:43:in `map'
/home/naitoh/.rvm/gems/ruby-2.5.1/gems/benchmark_driver-output-gruff-0.3.0/lib/benchmark_driver/output/gruff.rb:44:in `block (2 levels) in bulk_output': undefined method `values' for nil:NilClass (NoMethodError)
```

# Environment

* CentOS 7
* ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]
* benchmark_driver (0.13.3)
* benchmark_driver-output-gruff (0.3.0)

**Comment by k0kubun** [comment]
Thanks to report. It's gruff output plugin's bug. Will fix later

**Comment by naitoh** [comment]
I tried benchmark_driver v0.14.2.

```
$ cat test.yaml 

contexts:
  - gems: { csv: 1.0.0}

loop_count: 2000000
prelude: |
  class Array
    alias_method :blank?, :empty?
  end
  array = []
benchmark:
  empty: array.empty?
  blank: array.blank?
```

```
$ benchmark-driver test.yaml --output gruff
* empty...
  * csv 1.0.0...
* blank...
  * csv 1.0.0...
rendering graph...: graph.png
```

It worked fine.
Thank you for fixing!
