### ISSUE TITLE
Ruby Interface Example Does Not Work

### ISSUE THREAD

**Issue by AlessandroMinali** [benchmark-driver/benchmark-driver#77]
```
$ rvm list rubies
=* ruby-3.0.0 [ arm64 ]

# => - current
# =* - current && default
#  * - default
```

```ruby
3.0.0 :001 > require 'benchmark_driver'
 => true 
3.0.0 :002 > 
3.0.0 :003 > Benchmark.driver do |x|
3.0.0 :004">   x.prelude <<~RUBY
3.0.0 :005">     require 'active_support/all'
3.0.0 :006">     array = []
3.0.0 :007 >   RUBY
3.0.0 :008 > 
3.0.0 :009 >   x.report 'blank?', %{ array.blank? }
3.0.0 :010 >   x.report 'empty?', %{ array.empty? }
3.0.0 :011 > end
Warming up --------------------------------------
              blank?<internal:/Users/alessandro/.rvm/rubies/ruby-3.0.0/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- active_support/all (LoadError)
	from <internal:/Users/alessandro/.rvm/rubies/ruby-3.0.0/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /var/folders/5v/08fmfm517v15y8w58yjzb6x40000gn/T/benchmark_driver-20231010-76060-vd1tr2.rb:1:in `<main>'
/Users/alessandro/.rvm/gems/ruby-3.0.0/gems/benchmark_driver-0.16.4/lib/benchmark_driver/runner/ips.rb:155:in `execute': Failed to execute: /Users/alessandro/.rvm/rubies/ruby-3.0.0/bin/ruby /var/folders/5v/08fmfm517v15y8w58yjzb6x40000gn/T/benchmark_driver-20231010-76060-vd1tr2.rb (status: pid 76158 exit 1) (RuntimeError)
	from /Users/alessandro/.rvm/gems/ruby-3.0.0/gems/benchmark_driver-0.16.4/lib/benchmark_driver/runner/ips.rb:89:in `block (2 levels) in run_warmup'
	from /Users/alessandro/.rvm/gems/ruby-3.0.0/gems/benchmark_driver-0.16.4/lib/benchmark_driver/runner/ips.rb:145:in `block in with_script'
	from /Users/alessandro/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/tempfile.rb:317:in `open'
	from /Users/alessandro/.rvm/gems/ruby-3.0.0/gems/benchmark_driver-0.16.4/lib/benchmark_driver/runner/ips.rb:142:in `with_script'
	from /Users/alessandro/.rvm/gems/ruby-3.0.0/gems/benchmark_driver-0.16.4/lib/benchmark_driver/runner/ips.rb:88:in `block in run_warmup'
	from /Users/alessandro/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/tempfile.rb:317:in `open'
	from /Users/alessandro/.rvm/gems/ruby-3.0.0/gems/benchmark_driver-0.16.4/lib/benchmark_driver/runner/ips.rb:87:in `run_warmup'
	from /Users/alessandro/.rvm/gems/ruby-3.0.0/gems/benchmark_driver-0.16.4/lib/benchmark_driver/runner/ips.rb:36:in `block (3 levels) in run'
	from /Users/alessandro/.rvm/gems/ruby-3.0.0/gems/benchmark_driver-0.16.4/lib/benchmark_driver/output.rb:79:in `block in with_job'
	from /Users/alessandro/.rvm/gems/ruby-3.0.0/gems/benchmark_driver-0.16.4/lib/benchmark_driver/output/compare.rb:59:in `with_job'
	from /Users/alessandro/.rvm/gems/ruby-3.0.0/gems/benchmark_driver-0.16.4/lib/benchmark_driver/output.rb:78:in `with_job'
	from /Users/alessandro/.rvm/gems/ruby-3.0.0/gems/benchmark_driver-0.16.4/lib/benchmark_driver/runner/ips.rb:34:in `block (2 levels) in run'
	from /Users/alessandro/.rvm/gems/ruby-3.0.0/gems/benchmark_driver-0.16.4/lib/benchmark_driver/runner/ips.rb:31:in `map'
	from /Users/alessandro/.rvm/gems/ruby-3.0.0/gems/benchmark_driver-0.16.4/lib/benchmark_driver/runner/ips.rb:31:in `block in run'
	from /Users/alessandro/.rvm/gems/ruby-3.0.0/gems/benchmark_driver-0.16.4/lib/benchmark_driver/output/compare.rb:19:in `block in with_warmup'
	from /Users/alessandro/.rvm/gems/ruby-3.0.0/gems/benchmark_driver-0.16.4/lib/benchmark_driver/output/compare.rb:113:in `without_stdout_buffering'
	... 13 levels...
3.0.0 :012 > require 'active_support/all'
 => true 
```

**Comment by k0kubun** [comment]
I can do the same thing with no problem. I think it's specific to your environment and you haven't provided sufficient information to reproduce the issue.

```
$ ruby -v
ruby 3.0.1p64 (2021-04-05 revision 0fb782ee38) [x86_64-linux]

$ gem install benchmark_driver
Fetching benchmark_driver-0.16.4.gem
Successfully installed benchmark_driver-0.16.4
1 gem installed

$ gem install activesupport
Fetching concurrent-ruby-1.2.2.gem
Fetching activesupport-7.1.1.gem
Fetching tzinfo-2.0.6.gem
Fetching i18n-1.14.1.gem
Fetching connection_pool-2.4.1.gem
Successfully installed concurrent-ruby-1.2.2
Successfully installed tzinfo-2.0.6
Successfully installed i18n-1.14.1
Successfully installed connection_pool-2.4.1
Successfully installed activesupport-7.1.1
5 gems installed

$ gem list | grep activesupport
activesupport (7.1.1)

$ cat /tmp/a.rb
require 'benchmark_driver'

Benchmark.driver do |x|
  x.prelude <<~RUBY
    require 'active_support/all'
    array = []
  RUBY

  x.report 'blank?', %{ array.blank? }
  x.report 'empty?', %{ array.empty? }
end

$ ruby -v /tmp/a.rb
ruby 3.0.1p64 (2021-04-05 revision 0fb782ee38) [x86_64-linux]
Warming up --------------------------------------
              blank?    66.663M i/s -     66.986M times in 1.004855s (15.00ns/i, 68clocks/i)
              empty?    84.664M i/s -     85.204M times in 1.006385s (11.81ns/i, 29clocks/i)
Calculating -------------------------------------
              blank?   133.815M i/s -    199.988M times in 1.494518s (7.47ns/i, 26clocks/i)
              empty?   270.796M i/s -    253.991M times in 0.937942s (3.69ns/i, 4clocks/i)

Comparison:
              empty?: 270796475.3 i/s
              blank?: 133814574.0 i/s - 2.02x  slower
```

To remove the impact of anything specific to your environment, can you consider reproducing it with a Dockerfile, e.g. using `ubuntu:22.04`?
