### ISSUE TITLE
benchmark_driver 0.16.4 does not work

### ISSUE THREAD

**Issue by znz** [benchmark-driver/benchmark-driver#78]
```
% cat data/s.rb
require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'
  gem 'benchmark_driver', '0.16.4'
  #gem 'activesupport'
end

require 'benchmark_driver'

Benchmark.driver do |x|
  x.prelude <<~RUBY
    #require 'active_support/all'
    array = []
  RUBY

  #x.report %{ array.blank? }
  x.report %{ array.empty? }
end
% docker run --rm -it -v ./data:/data ruby:3.2.3 ruby /data/s.rb
Warming up --------------------------------------
       array.empty?     39.303M i/s -     39.601M times in 1.007577s/usr/local/bundle/gems/benchmark_driver-0.16.4/lib/benchmark_driver/output/compare.rb:161:in `/': String can't be coerced into Integer (TypeError)

    Integer(r/(1/hz))
		 ^^
	from /usr/local/bundle/gems/benchmark_driver-0.16.4/lib/benchmark_driver/output/compare.rb:161:in `estimate_clock'
	from /usr/local/bundle/gems/benchmark_driver-0.16.4/lib/benchmark_driver/output/compare.rb:102:in `show_durations'
	from /usr/local/bundle/gems/benchmark_driver-0.16.4/lib/benchmark_driver/output/compare.rb:66:in `with_job'
	from /usr/local/bundle/gems/benchmark_driver-0.16.4/lib/benchmark_driver/output.rb:78:in `with_job'
	from /usr/local/bundle/gems/benchmark_driver-0.16.4/lib/benchmark_driver/runner/ips.rb:34:in `block (2 levels) in run'
	from /usr/local/bundle/gems/benchmark_driver-0.16.4/lib/benchmark_driver/runner/ips.rb:31:in `map'
	from /usr/local/bundle/gems/benchmark_driver-0.16.4/lib/benchmark_driver/runner/ips.rb:31:in `block in run'
	from /usr/local/bundle/gems/benchmark_driver-0.16.4/lib/benchmark_driver/output/compare.rb:19:in `block in with_warmup'
	from /usr/local/bundle/gems/benchmark_driver-0.16.4/lib/benchmark_driver/output/compare.rb:113:in `without_stdout_buffering'
	from /usr/local/bundle/gems/benchmark_driver-0.16.4/lib/benchmark_driver/output/compare.rb:16:in `with_warmup'
	from /usr/local/bundle/gems/benchmark_driver-0.16.4/lib/benchmark_driver/output.rb:68:in `with_warmup'
	from /usr/local/bundle/gems/benchmark_driver-0.16.4/lib/benchmark_driver/runner/ips.rb:30:in `run'
	from /usr/local/bundle/gems/benchmark_driver-0.16.4/lib/benchmark_driver/runner.rb:46:in `block (4 levels) in run'
	from /usr/local/bundle/gems/benchmark_driver-0.16.4/lib/benchmark_driver/runner.rb:119:in `block in with_clean_env'
	from /usr/local/lib/ruby/3.2.0/bundler.rb:411:in `block in with_unbundled_env'
	from /usr/local/lib/ruby/3.2.0/bundler.rb:657:in `with_env'
	from /usr/local/lib/ruby/3.2.0/bundler.rb:411:in `with_unbundled_env'
	from /usr/local/bundle/gems/benchmark_driver-0.16.4/lib/benchmark_driver/runner.rb:118:in `with_clean_env'
	from /usr/local/bundle/gems/benchmark_driver-0.16.4/lib/benchmark_driver/runner.rb:45:in `block (3 levels) in run'
	from /usr/local/bundle/gems/benchmark_driver-0.16.4/lib/benchmark_driver/runner.rb:31:in `each'
	from /usr/local/bundle/gems/benchmark_driver-0.16.4/lib/benchmark_driver/runner.rb:31:in `block (2 levels) in run'
	from /usr/local/bundle/gems/benchmark_driver-0.16.4/lib/benchmark_driver/runner.rb:30:in `each'
	from /usr/local/bundle/gems/benchmark_driver-0.16.4/lib/benchmark_driver/runner.rb:30:in `block in run'
	from /usr/local/bundle/gems/benchmark_driver-0.16.4/lib/benchmark_driver/runner.rb:29:in `each'
	from /usr/local/bundle/gems/benchmark_driver-0.16.4/lib/benchmark_driver/runner.rb:29:in `run'
	from /usr/local/bundle/gems/benchmark_driver-0.16.4/lib/benchmark_driver/ruby_interface.rb:20:in `run'
	from /usr/local/bundle/gems/benchmark_driver-0.16.4/lib/benchmark_driver/ruby_interface.rb:4:in `run'
	from /usr/local/bundle/gems/benchmark_driver-0.16.4/lib/benchmark_driver.rb:16:in `driver'
	from /data/s.rb:11:in `<main>'
```

**Comment by k0kubun** [comment]
The exact same thing worked fine for me. So it's not an issue in benchmark_driver 0.16.4 but something specific to your environment. 

```
$ cat data/s.rb
require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'
  gem 'benchmark_driver', '0.16.4'
  #gem 'activesupport'
end

require 'benchmark_driver'

Benchmark.driver do |x|
  x.prelude <<~RUBY
    #require 'active_support/all'
    array = []
  RUBY

  #x.report %{ array.blank? }
  x.report %{ array.empty? }
end

$ docker run --rm -it -v ./data:/data ruby:3.2.3 ruby /data/s.rb
Warming up --------------------------------------
       array.empty?     88.755M i/s -     88.804M times in 1.000553s (11.27ns/i, 9clocks/i)
Calculating -------------------------------------
       array.empty?    295.722M i/s -    266.266M times in 0.900391s (3.38ns/i, 2clocks/i)
```

**Comment by palkan** [comment]
Hey @k0kubun,

> Since you're the only person who can reproduce it, I need you to investigate the reason yourself.

Well, I gonna be the second one 😁

The problem is with this line:

```ruby
hz = File.read('/proc/cpuinfo').scan(/cpu MHz\s+:\s+([\d\.]+)/){|(f)| break hz = Ration
al(f.to_f) * 1_000_000}
```

The `#scan` never finds a match, so `hz` is not redefined within the block. The `/proc/cpuinfo` (Docker on M1 Mac, Ruby 3.3 image) doesn't include MHz info (and it seems it's typical for ARM processors). Here is the full output:

```txt
processor       : 0
BogoMIPS        : 48.00
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm jscvt fcma lrcpc dcpop sha3 asimddp sha512 asimdfhm dit uscat ilrcpc flagm ssbs sb paca pacg dcpodp flagm2 frint
CPU implementer : 0x61
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0x000
CPU revision    : 0

processor       : 1
BogoMIPS        : 48.00
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm jscvt fcma lrcpc dcpop sha3 asimddp sha512 asimdfhm dit uscat ilrcpc flagm ssbs sb paca pacg dcpodp flagm2 frint
CPU implementer : 0x61
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0x000
CPU revision    : 0

processor       : 2
BogoMIPS        : 48.00
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm jscvt fcma lrcpc dcpop sha3 asimddp sha512 asimdfhm dit uscat ilrcpc flagm ssbs sb paca pacg dcpodp flagm2 frint
CPU implementer : 0x61
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0x000
CPU revision    : 0

processor       : 3
BogoMIPS        : 48.00
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm jscvt fcma lrcpc dcpop sha3 asimddp sha512 asimdfhm dit uscat ilrcpc flagm ssbs sb paca pacg dcpodp flagm2 frint
CPU implementer : 0x61
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0x000
CPU revision    : 0
```

Here is a quick fix: https://github.com/benchmark-driver/benchmark-driver/pull/79
